name: Reminder on Stale Issues

on:
    schedule:
        - cron: '0 5 * * *' # Every day at 05:00 UTC
    workflow_dispatch:

permissions:
    issues: write

jobs:
    reminder:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
            REPO: ${{ github.repository }}
            DAYS_TO_REMIND: '[1, 3, 5]' # Days to remind about open issues
        
        steps:
          - name: Get all open issues
            run: |
              gh issue list --repo "$REPO" --state open --json number,createdAt > issues.json

          - name: Post reminder comments
            run: |
              get_days_open() {
                  local created_at="$1"
                  local created_date="${created_at%%T*}"
                  local today_date=$(date -u +%F)
                  echo $(( ($(date -d "$today_date" +%s) - $(date -d "$created_date" +%s)) / 86400 + 1 ))
              }
                
              date_now=$(date +%s)
              jq -c '.[]' issues.json | while read -r issue; do

                  issue_number=$(echo "$issue" | jq '.number')
                  days_open=$(get_days_open "$(echo "$issue" | jq -r '.createdAt')")
                  
                  # for testing purposes
                  title=$(echo "$issue" | jq -r '.title')
                  if [ "$title" != "test_reminder" ]; then

                      for day in $(echo $DAYS_TO_REMIND | jq '.[]'); do
                          if [ "$days_open" -eq "$day" ]; then
                              comment="Auto-generated reminder: This issue has been open for $days_open days."
                              echo "Posting reminder to issue #$issue_number"
                              gh issue comment "$issue_number" --body "$comment" --repo "$REPO"
                          fi
                      done

                  fi
              done
            

            
